# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20160724_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='mobile_no',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
